# Generated by Django 3.0.8 on 2020-08-05 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusyKeys',
            fields=[
                ('guid', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('short_name', models.CharField(max_length=64)),
                ('full_name', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'busy_keys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BusyKeysReplacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=64)),
                ('dts', models.DateField(max_length=64)),
                ('f_key', models.CharField(max_length=64)),
                ('t_key', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'busy_keys_replacement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enterprises',
            fields=[
                ('guid', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'enterprises',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('guid', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=128)),
                ('middle_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('full_name', models.CharField(max_length=400)),
                ('gender_female', models.IntegerField()),
                ('snils_document', models.CharField(max_length=128)),
                ('tab_number', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'persons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonShedule',
            fields=[
                ('guid', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('begin_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'person_shedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('guid', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=400)),
                ('short_name', models.CharField(max_length=64)),
                ('mobile', models.IntegerField()),
            ],
            options={
                'db_table': 'positions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SheduleHours',
            fields=[
                ('guid', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('dts', models.DateField()),
                ('hours_full', models.SmallIntegerField()),
                ('hours_lite', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'shedule_hours',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shedules',
            fields=[
                ('guid', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'shedules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StaffHistory',
            fields=[
                ('guid', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('guid_type', models.CharField(max_length=150)),
                ('dts', models.DateTimeField()),
                ('rate', models.FloatField()),
            ],
            options={
                'db_table': 'staff_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StaffVacancy',
            fields=[
                ('guid', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('begin_date', models.DateField()),
                ('amount', models.FloatField()),
            ],
            options={
                'db_table': 'staff_vacancy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimeSheetPlane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_plane', models.DateField()),
                ('busykey_hours', models.FloatField()),
                ('busykey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TimeSheet.BusyKeys')),
                ('person', models.ForeignKey(db_column='person_guid', on_delete=django.db.models.deletion.CASCADE, to='TimeSheet.Persons')),
                ('position', models.ForeignKey(db_column='position_guid', on_delete=django.db.models.deletion.CASCADE, to='TimeSheet.Positions')),
                ('shedule', models.ForeignKey(db_column='guid', on_delete=django.db.models.deletion.CASCADE, to='TimeSheet.Shedules')),
            ],
        ),
    ]
