# Generated by Django 3.1 on 2021-01-21 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TimeSheet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='persons_coworks',
            fields=[
                ('dts', models.DateField(db_column='dts', primary_key=True, serialize=False, unique=True)),
                ('count_hours', models.FloatField(db_column='count_hours')),
                ('cowork_state', models.IntegerField(db_column='cowork_state')),
            ],
            options={
                'db_table': 'persons_coworks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='persons_reworks',
            fields=[
                ('dts', models.DateField(primary_key=True, serialize=False)),
                ('count_hours', models.FloatField()),
            ],
            options={
                'db_table': 'persons_reworks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PositionsReplacement',
            fields=[
                ('position_guid_from', models.CharField(db_column='position_guid_from', max_length=64, primary_key=True, serialize=False, unique=True)),
                ('position_guid_to', models.CharField(db_column='position_guid_to', max_length=64, unique=True)),
                ('replacement_type', models.IntegerField(db_column='replacement_type')),
            ],
            options={
                'db_table': 'positions_replacement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimeSheetFact',
            fields=[
                ('uid', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('amount', models.FloatField()),
            ],
            options={
                'db_table': 'shift_data_f',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='persons',
            options={'managed': False, 'ordering': ['full_name']},
        ),
        migrations.AlterModelOptions(
            name='timesheetplane',
            options={'managed': False, 'ordering': ['person_guid', 'dts']},
        ),
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_shop', models.CharField(blank=True, max_length=30)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TimeSheet.enterprises')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
