# Generated by Django 3.1 on 2021-03-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSheet', '0004_auto_20210202_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='enterprise_revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_date', models.DateField(db_column='change_date')),
            ],
            options={
                'db_table': 'enterprise_revision',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='person_statuses',
            fields=[
                ('person_guid', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False, unique=True)),
                ('work_status_id', models.IntegerField()),
                ('f_date', models.DateField()),
                ('e_date', models.DateField()),
            ],
            options={
                'db_table': 'person_statuses',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='profileuser',
            name='revisor',
            field=models.BooleanField(null=True),
        ),
    ]
