# Generated by Django 3.1 on 2021-03-23 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSheet', '0005_auto_20210323_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TimeSheet.enterprises'),
        ),
    ]
