# Generated by Django 3.1 on 2021-05-31 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSheet', '0006_auto_20210323_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='enterprise_revision_changes',
            fields=[
                ('uid', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('changetype', models.CharField(db_column='changetype', max_length=64)),
                ('changetime', models.DateField(db_column='changetime')),
            ],
            options={
                'db_table': 'enterprise_revision_changes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='persons_extended_info',
            fields=[
                ('person_guid', models.ForeignKey(db_column='person_guid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='TimeSheet.persons')),
                ('dts', models.DateField(db_column='dts')),
                ('status_id', models.IntegerField(db_column='status_id')),
            ],
            options={
                'db_table': 'persons_extended_info',
                'managed': False,
            },
        ),
    ]
