# Generated by Django 4.1.4 on 2022-12-15 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSheet', '0008_check_names_covid19_dtype_covid19_reply_codes_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='settingtabletemp',
            table='TimeSheet_settingtabletemp',
        ),
    ]
